batch_size: 4
dataset_name: cnn_dailymail
learning_rate: 0.00010958308743118596
max_length: 512
model_name: google-t5/t5-small
optimizer_name: rmsprop
seed_num: 1
test_range: 35
train_range: 350
val_range: 35
